run_date_std=2026-02-18
hive_jdbc_url=jdbc:hive2://127.0.0.1:10000/default
hive_user=hive
warehouse_external_dir=/Users/xiongyuc/workspace/hive_native/hadoop_data/warehouse/external
warehouse_managed_dir=/Users/xiongyuc/workspace/hive_native/hadoop_data/warehouse/managed
